
version: "3.8"

services:
  db:
    image: mysql:8.4
    container_name: warehousedb
    environment:
      MYSQL_DATABASE: datawarehouse
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  spring-app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://db:3306/datawarehouse
      DB_USERNAME: user
      DB_PASSWORD: password
    depends_on:
      - db

volumes:
  db_data:
